import type { Metadata } from 'next';
import { StoreProvider } from './StoreProvider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { StyledEngineProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import './globals.css';
import PrivateRoute from '@/components/PrivateRoute';
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'REST GraphQL Client',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StoreProvider>
          <CssBaseline />
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <PrivateRoute>
              <StyledEngineProvider injectFirst>
                <Header />
                {children}
                <Footer />
                <Toaster expand={false} richColors closeButton duration={5000} className="bottom-24" />
              </StyledEngineProvider>
            <Toaster expand={false} richColors closeButton duration={3000} className="bottom-24" />
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
