import type { Metadata } from 'next';
import { StoreProvider } from './StoreProvider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import PrivateRoute from '@/components/PrivateRoute';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CssBaseline from '@mui/material/CssBaseline';
import { StyledEngineProvider, ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'REST GraphQL Client',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${inter.variable}`}>
        <StoreProvider>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <StyledEngineProvider injectFirst>
                <NextIntlClientProvider messages={messages}>
                  <Header />
                  <PrivateRoute>{children}</PrivateRoute>
                  <Footer />
                  <Toaster expand={false} richColors closeButton duration={3000} className="bottom-24" />
                </NextIntlClientProvider>
              </StyledEngineProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
